//
// Generated file, do not edit! Created by opp_msgtool 6.0 from DataPkt.msg.
//

#ifndef __DATAPKT_M_H
#define __DATAPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DataPkt;
/**
 * Class generated from <tt>DataPkt.msg:1</tt> by opp_msgtool.
 * <pre>
 * packet DataPkt
 * {
 *     simtime_t timeStampTx;
 * }
 * </pre>
 */
class DataPkt : public ::omnetpp::cPacket
{
  protected:
    omnetpp::simtime_t timeStampTx = SIMTIME_ZERO;

  private:
    void copy(const DataPkt& other);

  protected:
    bool operator==(const DataPkt&) = delete;

  public:
    DataPkt(const char *name=nullptr, short kind=0);
    DataPkt(const DataPkt& other);
    virtual ~DataPkt();
    DataPkt& operator=(const DataPkt& other);
    virtual DataPkt *dup() const override {return new DataPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual omnetpp::simtime_t getTimeStampTx() const;
    virtual void setTimeStampTx(omnetpp::simtime_t timeStampTx);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DataPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DataPkt& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DataPkt *fromAnyPtr(any_ptr ptr) { return check_and_cast<DataPkt*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DATAPKT_M_H

