//
// Generated file, do not edit! Created by opp_msgtool 6.0 from FeedbackPkt.msg.
//

#ifndef __FEEDBACKPKT_M_H
#define __FEEDBACKPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class FeedbackPkt;
/**
 * Enum generated from <tt>FeedbackPkt.msg:1</tt> by opp_msgtool.
 * <pre>
 * enum typePkt
 * {
 *     DATA = 0;
 *     FEEDBACK = 2;
 * }
 * </pre>
 */
enum typePkt {
    DATA = 0,
    FEEDBACK = 2
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const typePkt& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, typePkt& e) { int n; b->unpack(n); e = static_cast<typePkt>(n); }

/**
 * Class generated from <tt>FeedbackPkt.msg:6</tt> by opp_msgtool.
 * <pre>
 * packet FeedbackPkt
 * {
 *     int currentBufferSize;
 *     int bufferSize;
 *     simtime_t timeStampRx;
 * }
 * </pre>
 */
class FeedbackPkt : public ::omnetpp::cPacket
{
  protected:
    int currentBufferSize = 0;
    int bufferSize = 0;
    omnetpp::simtime_t timeStampRx = SIMTIME_ZERO;

  private:
    void copy(const FeedbackPkt& other);

  protected:
    bool operator==(const FeedbackPkt&) = delete;

  public:
    FeedbackPkt(const char *name=nullptr, short kind=0);
    FeedbackPkt(const FeedbackPkt& other);
    virtual ~FeedbackPkt();
    FeedbackPkt& operator=(const FeedbackPkt& other);
    virtual FeedbackPkt *dup() const override {return new FeedbackPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getCurrentBufferSize() const;
    virtual void setCurrentBufferSize(int currentBufferSize);

    virtual int getBufferSize() const;
    virtual void setBufferSize(int bufferSize);

    virtual omnetpp::simtime_t getTimeStampRx() const;
    virtual void setTimeStampRx(omnetpp::simtime_t timeStampRx);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FeedbackPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FeedbackPkt& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline FeedbackPkt *fromAnyPtr(any_ptr ptr) { return check_and_cast<FeedbackPkt*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __FEEDBACKPKT_M_H

